name-template: 'v$NEXT_PATCH_VERSION'
prerelease: false
categories:
  - title: 'Breaking Changes'
    labels: ['breaking']
  - title: 'Features'
    labels: ['feature', 'enhancement']
  - title: 'Fixes'
    labels: ['bug', 'fix']
  - title: 'Docs'
    labels: ['documentation']
  - title: 'CI/CD'
    labels: ['ci']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '
'
replacers: []
template: |
  ## Changes
  $CHANGES
